thinkncenturies/semicolon/urls.py
from django.conf.urls import url
from . import views

app_name = 'semicolon'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # url(r'^submit/', ),
]

thinkncenturies/thinkncenturies/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from django.contrib import admin
# from rest_framework import routers, serializers, viewsets


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^semicolon/', include('semicolon.urls')),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^grappelli/', include('grappelli.urls')),
]

thinkncenturies/semicolon/models.py
from django.utils import timezone
from django.db import models


class Post(models.Model):
    FICTION = 'FICTION'
    NONFICTION = 'NONFICTION'
    POETRY = 'POETRY'
    ESSAY = 'ESSAY'

    GENRE_CHOICES = (
        (FICTION , 'Fiction'),
        (NONFICTION , 'Nonfiction'),
        (POETRY , 'Poetry'),
        (ESSAY , 'Essay'),
    )

    genre = models.CharField(
        default='Undefined',
        choices=GENRE_CHOICES,
        max_length=255,
    )
    title = models.CharField(
        default='',
        max_length=255,
    )
    author = models.CharField(
        default='',
        max_length=255,
    )
    body = models.TextField(
        default='',
        blank=False,
    )
    created_on = models.DateTimeField(
        default=timezone.now,
    )

    def __str__(self):
        return self.title

thinkncenturies/semicolon/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Post


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'semicolon/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """Return the last five published posts. """
        return Post.objects.order_by('-created_on')[:5]

class DetailView(generic.DetailView):
    model = Post
    template_name = 'semicolon/detail.html'

thinkncenturies/semicolon/templates/semicolon/detail.html
<!-- /*<style>

.body {
    background-color: slategrey;
}

.container {
    background-color: #000000;
    color: #FFFFFF;
}

.header {
    background-color: skyblue;
    height: 50px;
    font-family: helvetica, verdana, trebuchet;
    font-size: 20;
}

.subheader {
    background-color: darkblue;
}


</style>*/ -->

<body class="body">

<div class="header" align="center">
    Semicolon
</div>

<div class="subheader">
</br>
</div>

<div class="container">
    <strong>Title:</strong>
        {{ post.title }}
    </br></br>

    <strong>Author:</strong>
      {{ post.author }}
    </br></br>

    <strong>Genre:</strong>
      {{ post.genre }}
    </br></br>

    <strong>Body:</strong>
      {{ post.body }}
      </br></br>

</div>
</body>

thinkncenturies/semicolon/templates/semicolon/index.html
{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li><a href="{% url 'semicolon:detail' post.id %}">
          {{ post.title }}
        </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}